spring:
  application:
    name: gateway-mvc
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service #routing 정보를 구분하기 위한 id
              uri: lb://USER-SERVICE #어디로 갈것인가 현재 user-service application.yaml 랜덤포트이므로 lb://USER-SERVICE
              predicates:
                - Path=/user-service/** #어떠한 요청이 왔을 때 uri로 보낼것인가
              filters:
#                - RewritePath=/user-service/(?<segment>.*), /$\{segment} #/user-service(이 부분 제거)/api/users
                - StripPrefix=1 #origin/endpoint 첫 번째 endpoint 제거 위 RewritePath랑 같은 효과
                - AddRequestHeader=add-request-header-value, add-request-header-key
                - AddResponseHeader=add-response-header-value, add-response-header-key

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
